---
author: Grey Gergen
title: Project Dataset and Topics
output: html
---

[Link to dataset](https://www.openbrewerydb.org/documentation)

Things you plan to investigate using this dataset:

- Location(s) of breweries
- Naming of breweries
- Types of breweries
- Taking elements from websites of breweries

Stat 351 topics you plan to cover during the analysis:

1. Reading in API data
2. Parsing JSON
3. Scraping data from websites
4. Using appropriate graphics

```{r}
library(httr)
library(jsonlite)
library(tidyverse)

brew <- fromJSON("https://api.openbrewerydb.org/v1/breweries")
```

---

Comments:

- Breweries don't have a standard website format, so this is likely to be a bit more challenging than you expect to get systematic data back out.

- What do you plan to do with the naming of breweries? What type of analysis/investigation can you do with that?

Look for common naming or most used words. See if region has any significance with naming.

- A spatial analysis of whether breweries in similar areas/close proximity tend to specialize vs. compete might be interesting -- I have no idea if the data supports this or not. You could limit it to one or two cities known for having a ton of breweries, though?

I like the spatial analysis and will probably end up doing something with that.

- Do some digging to ensure that this data is relatively complete before you settle on it -- if only so that you can acknowledge the limitations of your dataset. 

Looks pretty complete. I used fromJSON and returned a cleaned dataset on this script.
